print('Welcome to Generator for Link for Your Site!')
print('Complete with the infomations below ⬇️')
print()
name = input('What\'s your name?: ').lower()
print()
name_of_pet_of_the_person = input('What\'s your name of pet?: ').lower()
print()
print(f'The name of your site could be https://www.{name}-{name_of_pet_of_the_person}.com or http://www.{name}-{name_of_pet_of_the_person}.com')
print('\n')
print('Observation:')
print('URL is only lowercase letter!')